package is.Interpreter.Parsing;

public enum Simbolo {
    CHAR_INVALIDO, PAROLA, TONDA_APERTA, TONDA_CHIUSA, COMMA, STRINGA_QUOTATA, EOF, CREATE, REMOVE, LIST, MOVE, 
    MOVEOFF, SCALE, GROUP, UNGROUP, PERIMETER, AREA, CIRCLE, RECTANGLE, IMAGE, ALL, GROUPS
}
